version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo_node_express
    ports:
      - "3011"
    environment:
      - NODE_ENV=production
      - PORT=3011
    restart: unless-stopped
